### ISSUE TITLE
How to use with SWD / SWO / semihosting?

### ISSUE THREAD

**Issue by amq** [ARMmbed/mbed-trace#67]
See also https://github.com/ARMmbed/mbed-drivers/issues/188

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSYST-2179

**Comment by jupe** [comment]
Here is examples how to set up SWO traces:
https://developer.mbed.org/users/wim/code/SWO/docs/e5af2e131b95/SWO_8cpp_source.html

So all what you have to do is just redirect mbed-traces to use something like `SWO_PrintString()` -function using `mbed_trace_print_function_set()` -API.

related to: https://github.com/mbedmicro/DAPLink/issues/259

Is this what you are looking for?

**Comment by zxfeei** [comment]
@jupe  Thanks for your help.   I want to  kown  DAPlink how  to support SWO trace ，but not ST-LINK  and Segger J-Link.

**Comment by amq** [comment]
@jupe, thanks!

For those who are looking for a full example:

```c
#if MBED_CONF_MBED_TRACE_ENABLE
#include "mbed-trace/mbed_trace.h"
#include "swo.h"
// #include "swo-platform/swo-platform.h" // for efm32

#define TRACE_GROUP "main"

void trace_printer(const char* str) {
    swoprintf("%s\n", str);
}
#endif

int main() {
    mbed_trace_init();
    mbed_trace_print_function_set(trace_printer);

    float x = 1.2;
    tr_debug("Result:");
    tr_debug("%f", x * x);
}
```
