### ISSUE TITLE
mbed-trace dummies defines and original functions declaration are different

### ISSUE THREAD

**Issue by yogpan01** [ARMmbed/mbed-trace#70]
1.Use some of mbed-trace functions in your application, for example use
int int_var;
int_var = mbed_trace_init(); 
function in your main. 
The real function declaration is :
int mbed_trace_init( void );
2. Disable mbed enabling flag MBED_CONF_MBED_TRACE_ENABLE
Expected result:
The code will be compiled without an error.
Actual result:
As mbed enabling flag was disabled, all functions defined by dummies.
mbed_trace_init ->
#define mbed_trace_init(...) ((void) 0)
As mbed_trace_init() dummy define is different from original declaration , we get this error:
a value of type "void" cannot be assigned to an entity of type "int"
./mbed-cloud-client/factory-configurator-client/mbed-trace-helper/source/mbed-trace-helper.c: 0 warnings, 1 error

**Comment by yogpan01** [comment]
@jupe Please resolve this issue.
@shelib01 @TaniaMirzin FYI

**Comment by jupe** [comment]
looks that init function is only one which is incorrectly defined in dummy defines. Could you verify it?

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSYST-2453

**Comment by jupe** [comment]
Fix is coming here: #71

**Comment by jupe** [comment]
This should be fixed by #71. Also included in latest release v1.3.0
