### ISSUE TITLE
Possible deadlock using mutexes in mbed-trace.

### ISSUE THREAD

**Issue by korjaa** [ARMmbed/mbed-trace#74]
With intensive printing I think I'm having issue with some sort of deadlock by mbed-trace.

Test to reproduce:
https://github.com/ARMmbed/mbed-trace/pull/73

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSYST-2476

**Comment by korjaa** [comment]
I was just told I'm not using recursive mutexes when I should have :)

What I should have done:
```
pthread_mutexattr_t stdout_mutex_attr;
pthread_mutexattr_init(&stdout_mutex_attr);
pthread_mutexattr_settype(&stdout_mutex_attr, PTHREAD_MUTEX_RECURSIVE);
pthread_mutex_init(&stdout_mutex, &stdout_mutex_attr);
```

What I did:
```
pthread_mutex_init(&stdout_mutex, NULL);
```

I think this recursive mutex requirement should be added to the README.md.

**Comment by korjaa** [comment]
So it's highly likely this issue isn't real, I was just using it wrongly.

**Comment by korjaa** [comment]
Changed from bug to enhancement, because just stating recursive mutex requirement on README.md would be enough I think.

**Comment by tommikas** [comment]
The mbed_trace.h header mentions this here: https://github.com/ARMmbed/mbed-trace/blob/master/mbed-trace/mbed_trace.h#L254-L255

But yeah, I agree it should be mentioned in the readme too.

**Comment by tommikas** [comment]
Documentation updated.
